#!/bin/sh
username="$(id -u -n)"
if [ "$username" = "clo" ]; then
  name="clover"
elif [ "$username" = "nmarks" ]; then
  name="natalie"
elif [ "$username" = "fish" ]; then
  name="fish"
fi
if [ -z "$name" ]; then
  echo "Configure this wrapper script with your name." >&2
  exit 1
fi
exec nix run ".#nvim-$name" -- "$@"
